title: Codific mvc567

theme: jekyll-theme-minimal

search_enabled: true

collections:
  01_getting_started:
    output: true

defaults:
  - scope:
      path: ""
      type: 01_getting_started
    values:
      layout: null
      permalink: /01_getting_started/:name
